# Railway service configuration
[service]
name = "courier-bot"
start = "python3 bot.py"

# Enable graceful shutdown and zero-downtime deployments
[deploy]
startCommand = "python3 bot.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build]
builder = "nixpacks"

[variables]
# Set these in Railway Dashboard (Environment Variables)
# BOT_TOKEN, ADMIN_ID, ADMIN_CHAT, ORDER_CHAT, API_ID, API_HASH, DB_NAME, DEFAULT_OPERATOR_PAY, DEFAULT_COURIER_PAY, DEFAULT_PETROL
# Persist DB on Railway volume (recommended):
DB_DIR = "/data"
DB_NAME = "database.db"
DB_PATH = "/data/database.db"

[nixpacks]
python_version = "3.12"
auto_clean = true
install = "pip install --timeout 300 --retries 5 -r requirements.txt"

