# Railway service configuration
[service]
name = "courier-bot"
start = "python3 bot.py"

# Enable graceful shutdown and zero-downtime deployments
[deploy]
startCommand = "python3 bot.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build]
builder = "nixpacks"

[variables]
# Set these in Railway Dashboard (Environment Variables)
# REQUIRED: BOT_TOKEN, SUPABASE_URL, SUPABASE_ANON_KEY
# Optional: SUPABASE_SECRET_KEY, ADMIN_ID, ADMIN_CHAT, ORDER_CHAT, API_ID, API_HASH
# Note: We no longer use SQLite - all data is in Supabase

[nixpacks]
python_version = "3.12"
auto_clean = true
install = "pip install --timeout 300 --retries 5 -r requirements.txt"

